"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v$iu61k_n!o5b0-cky0j)!cxeepebpk!81=-+ivj&jjwcg364*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
import os

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
 
 
EMAIL_FROM = 'hishamarshad46@gmail.com'
EMAIL_BCC = ''  # Leave this empty if you don't need BCC
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hishamarshad46@gmail.com'
EMAIL_HOST_PASSWORD = 'xqxgcseaedsleskx'  # Replace 'your_gmail_password' with your Gmail password
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Application definition


 
 
 

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
	'rest_framework.authtoken',
    # 'oauth2_provider',
    'social_django',
    'corsheaders',

    # 'rest_framework_social_oauth2',
    'authemail',
    'accounts',
    'chat',
    'channels'
]
ASGI_APPLICATION = "backend.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
STREAM_API_KEY = 'b82m6m95jajk' # https://getstream.io/dashboard/
STREAM_API_SECRET = 'eduj6gvkjd87ewfuruum3p4r8tj2g479sa8ehquxycgsb3jbuwp4mf3js9q88mhj'
 
AUTH_USER_MODEL = 'accounts.myUser'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
     
    ),
}
 
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '726758745941-6d4jjuqfuveumoikug4jmteoo1mj5kt2.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
LOGIN_URL = 'login'  # Set this to the URL where users are redirected if they need to log in
LOGIN_REDIRECT_URL = '/'  # Set this to the desired URL where users are redirected after a successful login
AUTH_EMAIL_VERIFICATION = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
         
                # 'social_django.context_processors.backends',
                # 'social_django.context_processors.login_redirect',
            ],
        },
    },
]
# Make sure 'APP_DIRS' is set to True
TEMPLATES[0]['APP_DIRS'] = True

# Specify the path to your app-specific templates directory
TEMPLATES[0]['DIRS'].append(os.path.join(BASE_DIR, 'accounts/templates'))

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "pakages",
        "TEST": {
            "NAME": BASE_DIR / "db.sqlite3",
        },
        "HOST": "127.0.0.1",
        "PASSWORD": "kkllBB#46",
        "USER": "root",
        "PORT": 3306,
    },
    
}

 
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# CORS settings
CORS_ALLOW_ALL_ORIGINS = False  # Set to True to allow all origins (not recommended for production)
CORS_ALLOW_CREDENTIALS = True   # Set to True if your frontend sends cookies with requests
CORS_ALLOWED_ORIGINS = [        # List the allowed origins (e.g., your frontend domain)
    "http://localhost:5173",    # Add the actual domain of your React app
]
 
